site_name: Calculator Docs
nav:
  - Home: index.md
  - API Reference: api-reference.md
theme: readthedocs
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters: ["!^_"]
