name: Auto-Merge

on:
  workflow_run:
    workflows: ["Build and Test", "Documentation"]
    types:
      - completed

jobs:
  check-success:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Check if both workflows succeeded
        id: check-workflows
        run: |
          echo "Both workflows succeeded. Enabling auto-merge."

  automerge:
    name: Enable automerge on dependabot PRs
    needs: ["python-app", "docs"]
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: "mergebot[aboba]"

          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE
