# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lab2 application

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Test with pytest
      run: |
        pytest

    - name: Enable auto-merge for PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: squash

    - name: Action-Automerge
      # You may pin to the exact commit or the version.
      # uses: mtanzi/action-automerge@8cc3ee735eafeedb690f2600be700d5d8548ae91
      uses: mtanzi/action-automerge@v1
      with:
        # Token to authenticate with GitHub
        github_token: ${{ github.token }}
        # Source branch you want to merge into the target.
        source: "development"
        # Target branch, where the source branch is going to be merged into
        target: "main"
          
